##############################################################################
# NVIDIA Remote Stream (NVRS) - Production Docker Compose
#
# Runs on the gateway EC2 instance. Provides the control plane API,
# a local PostgreSQL (for dev/single-node; prod uses RDS), Redis, and
# an Nginx reverse proxy with TLS termination.
#
# Usage:
#   docker compose -f deploy-compose.yml up -d
#
# The .env file must be present in the same directory.
##############################################################################

services:
  # ---------------------------------------------------------------------------
  # Nginx - TLS termination and reverse proxy
  # ---------------------------------------------------------------------------
  nginx:
    image: nginx:1.27-alpine
    container_name: nvrs-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      server-api:
        condition: service_healthy
    restart: always
    networks:
      - nvrs-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO /dev/null http://localhost:80/nginx-health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # ---------------------------------------------------------------------------
  # Server API - NestJS control plane
  # ---------------------------------------------------------------------------
  server-api:
    image: ghcr.io/nvremote/server-api:latest
    container_name: nvrs-api
    build:
      context: /opt/nvrs/server-api-src
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://nvrs:${DB_PASSWORD}@postgres:5432/nvrs?schema=public
      - REDIS_URL=redis://redis:6379
    expose:
      - "3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - nvrs-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/api/v1/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "5"

  # ---------------------------------------------------------------------------
  # PostgreSQL - Local database (dev/single-node mode)
  # In production with RDS, remove this service and update DATABASE_URL in .env.
  # ---------------------------------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: nvrs-postgres
    environment:
      POSTGRES_DB: nvrs
      POSTGRES_USER: nvrs
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    networks:
      - nvrs-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nvrs -d nvrs"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    shm_size: "128mb"

  # ---------------------------------------------------------------------------
  # Redis - Session cache and WebSocket pub/sub
  # ---------------------------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: nvrs-redis
    command: >
      redis-server
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redisdata:/data
    expose:
      - "6379"
    restart: always
    networks:
      - nvrs-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 192M
        reservations:
          memory: 64M
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

# ---------------------------------------------------------------------------
# Networks
# ---------------------------------------------------------------------------
networks:
  nvrs-net:
    driver: bridge
    name: nvrs-net

# ---------------------------------------------------------------------------
# Volumes
# ---------------------------------------------------------------------------
volumes:
  pgdata:
    name: nvrs-pgdata
  redisdata:
    name: nvrs-redisdata
