#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Installs the NVRemote Host Agent as a Windows service.

.DESCRIPTION
    This script performs the following steps:
    1. Verifies administrator privileges
    2. Creates the ProgramData directory structure
    3. Copies the agent binary to the install directory
    4. Prompts for control plane URL and bootstrap token
    5. Writes the configuration file
    6. Installs and starts the Windows service
    7. Verifies registration with the control plane

.PARAMETER BinaryPath
    Path to the built nvremote-agent.exe binary. Defaults to the binary in the current directory.

.PARAMETER ControlPlaneURL
    URL of the NVRemote control plane. If not provided, the script will prompt.

.PARAMETER BootstrapToken
    Bootstrap token for host registration. If not provided, the script will prompt.

.PARAMETER Silent
    Run without interactive prompts. Requires ControlPlaneURL and BootstrapToken parameters.
#>

param(
    [string]$BinaryPath = ".\nvremote-agent.exe",
    [string]$ControlPlaneURL = "",
    [string]$BootstrapToken = "",
    [switch]$Silent
)

$ErrorActionPreference = "Stop"

$InstallDir = "C:\ProgramData\NVRemote"
$AgentBinary = Join-Path $InstallDir "nvremote-agent.exe"
$ConfigFile = Join-Path $InstallDir "agent.yaml"
$ServiceName = "NVRemoteAgent"

function Write-Step {
    param([string]$Message)
    Write-Host "[*] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[+] $Message" -ForegroundColor Green
}

function Write-Failure {
    param([string]$Message)
    Write-Host "[-] $Message" -ForegroundColor Red
}

# --- Step 1: Verify administrator privileges ---
Write-Step "Checking administrator privileges..."
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Failure "This script must be run as Administrator."
    Write-Host "Right-click PowerShell and select 'Run as Administrator', then try again."
    exit 1
}
Write-Success "Running with administrator privileges."

# --- Step 2: Verify the agent binary exists ---
Write-Step "Locating agent binary..."
if (-not (Test-Path $BinaryPath)) {
    Write-Failure "Agent binary not found at: $BinaryPath"
    Write-Host "Build the agent first with: make build"
    exit 1
}
Write-Success "Agent binary found: $BinaryPath"

# --- Step 3: Create install directory ---
Write-Step "Creating install directory: $InstallDir"
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}
Write-Success "Install directory ready."

# --- Step 4: Copy binary ---
Write-Step "Copying agent binary to $AgentBinary..."
Copy-Item -Path $BinaryPath -Destination $AgentBinary -Force
Write-Success "Binary copied."

# --- Step 5: Collect configuration ---
Write-Step "Configuring the agent..."

if ([string]::IsNullOrEmpty($ControlPlaneURL)) {
    if ($Silent) {
        Write-Failure "ControlPlaneURL is required in silent mode."
        exit 1
    }
    $ControlPlaneURL = Read-Host "Enter the Control Plane URL (e.g., https://nvremote.example.com)"
}

if ([string]::IsNullOrEmpty($BootstrapToken)) {
    if ($Silent) {
        Write-Failure "BootstrapToken is required in silent mode."
        exit 1
    }
    $BootstrapToken = Read-Host "Enter the Bootstrap Token"
}

$hostname = $env:COMPUTERNAME

# --- Step 6: Write configuration file ---
Write-Step "Writing configuration to $ConfigFile..."

$configContent = @"
# NVRemote Host Agent Configuration
# Generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

control_plane_url: "$ControlPlaneURL"
bootstrap_token: "$BootstrapToken"
host_name: "$hostname"
streamer_path: "C:\\Program Files\\NVRemote\\nvremote-host.exe"
stun_servers:
  - "stun.l.google.com:19302"
data_dir: "$InstallDir"
log_level: "info"
"@

Set-Content -Path $ConfigFile -Value $configContent -Encoding UTF8
Write-Success "Configuration written."

# --- Step 7: Install the Windows service ---
Write-Step "Installing Windows service: $ServiceName..."

# Stop existing service if running.
$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingService) {
    Write-Step "Stopping existing service..."
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    & $AgentBinary --uninstall 2>$null
    Start-Sleep -Seconds 2
}

& $AgentBinary --install
if ($LASTEXITCODE -ne 0) {
    Write-Failure "Failed to install the service."
    exit 1
}
Write-Success "Service installed."

# --- Step 8: Start the service ---
Write-Step "Starting service..."
Start-Service -Name $ServiceName
Start-Sleep -Seconds 3

$svc = Get-Service -Name $ServiceName
if ($svc.Status -eq "Running") {
    Write-Success "Service is running."
} else {
    Write-Failure "Service failed to start. Check logs in $InstallDir"
    exit 1
}

# --- Step 9: Verify registration ---
Write-Step "Verifying registration..."
$registrationFile = Join-Path $InstallDir "registration.json"

# Wait up to 30 seconds for registration to complete.
$maxWait = 30
$waited = 0
while (-not (Test-Path $registrationFile) -and $waited -lt $maxWait) {
    Start-Sleep -Seconds 2
    $waited += 2
}

if (Test-Path $registrationFile) {
    $reg = Get-Content $registrationFile | ConvertFrom-Json
    Write-Success "Host registered successfully!"
    Write-Host "  Host ID:    $($reg.host_id)"
    Write-Host "  Tunnel IP:  $($reg.tunnel_ip)"
} else {
    Write-Failure "Registration file not found after ${maxWait}s. Check agent logs."
    Write-Host "You can check the service status with: Get-Service $ServiceName"
    Write-Host "View logs with: Get-Content $InstallDir\agent.log"
}

Write-Host ""
Write-Success "Installation complete!"
Write-Host "  Service:  $ServiceName"
Write-Host "  Config:   $ConfigFile"
Write-Host "  Data Dir: $InstallDir"
