#!/usr/bin/env bash
# ============================================================================
# NVRemote Host Agent — Linux Installer
#
# Usage:
#   chmod +x install.sh && ./install.sh
#
# This script:
#   1. Detects GPU and platform (desktop/Jetson/DGX Spark)
#   2. Copies the agent to /usr/local/bin/
#   3. Creates a systemd service
#   4. Runs the first-time setup if no config exists
# ============================================================================

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/nvremote"
DATA_DIR="/var/lib/nvremote"
SERVICE_NAME="nvremote-agent"
BINARY_NAME="NVRemoteAgent"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[*]${NC} $1"; }
ok()    { echo -e "${GREEN}[+]${NC} $1"; }
fail()  { echo -e "${RED}[-]${NC} $1"; }

# --- Check for root ---
if [ "$(id -u)" -ne 0 ]; then
    fail "This script must be run as root (use sudo)."
    exit 1
fi

# --- Find the binary ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENT_BIN="${SCRIPT_DIR}/${BINARY_NAME}"

if [ ! -f "$AGENT_BIN" ]; then
    fail "Agent binary not found at: $AGENT_BIN"
    echo "  Make sure ${BINARY_NAME} is in the same directory as this script."
    exit 1
fi

info "Found agent binary: ${AGENT_BIN}"

# --- Detect GPU ---
info "Detecting GPU..."
if command -v nvidia-smi &>/dev/null; then
    GPU=$(nvidia-smi --query-gpu=name --format=csv,noheader,nounits 2>/dev/null | head -1 || echo "unknown")
    ok "GPU detected: ${GPU}"
else
    GPU="unknown"
    info "nvidia-smi not found — GPU will be detected at runtime."
fi

# --- Install binary ---
info "Installing ${BINARY_NAME} to ${INSTALL_DIR}..."
cp "$AGENT_BIN" "${INSTALL_DIR}/${BINARY_NAME}"
chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
ok "Binary installed."

# --- Create directories ---
mkdir -p "$CONFIG_DIR" "$DATA_DIR"

# --- Create systemd service ---
info "Creating systemd service: ${SERVICE_NAME}"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=NVRemote Host Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/${BINARY_NAME} -config ${CONFIG_DIR}/agent.yaml -run
Restart=on-failure
RestartSec=5
Environment=NVREMOTE_DATA_DIR=${DATA_DIR}
WorkingDirectory=${DATA_DIR}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
ok "Systemd service created."

# --- First-time config ---
if [ ! -f "${CONFIG_DIR}/agent.yaml" ]; then
    echo
    info "First-time setup — let's configure the agent."
    echo

    read -rp "  Bootstrap Token: " BOOTSTRAP_TOKEN
    if [ -z "$BOOTSTRAP_TOKEN" ]; then
        fail "Bootstrap token is required."
        exit 1
    fi

    read -rp "  Control Plane URL [https://api.nvremote.com]: " CONTROL_PLANE_URL
    CONTROL_PLANE_URL="${CONTROL_PLANE_URL:-https://api.nvremote.com}"

    HOSTNAME=$(hostname)
    read -rp "  Host Name [${HOSTNAME}]: " HOST_NAME
    HOST_NAME="${HOST_NAME:-$HOSTNAME}"

    cat > "${CONFIG_DIR}/agent.yaml" <<EOF
# NVRemote Host Agent Configuration
# Generated by install.sh

control_plane_url: "${CONTROL_PLANE_URL}"
bootstrap_token: "${BOOTSTRAP_TOKEN}"
host_name: "${HOST_NAME}"
streamer_path: "/usr/local/bin/nvremote-host"
stun_servers:
  - "stun.l.google.com:19302"
data_dir: "${DATA_DIR}"
log_level: "info"
EOF

    chmod 600 "${CONFIG_DIR}/agent.yaml"
    ok "Config written to ${CONFIG_DIR}/agent.yaml"
else
    ok "Config already exists at ${CONFIG_DIR}/agent.yaml"
fi

# --- Enable and start ---
info "Enabling and starting ${SERVICE_NAME}..."
systemctl enable "$SERVICE_NAME" --quiet
systemctl start "$SERVICE_NAME"

if systemctl is-active --quiet "$SERVICE_NAME"; then
    ok "Service is running!"
else
    fail "Service failed to start. Check: journalctl -u ${SERVICE_NAME}"
    exit 1
fi

echo
ok "Installation complete!"
echo "  Service:  ${SERVICE_NAME}"
echo "  Config:   ${CONFIG_DIR}/agent.yaml"
echo "  Logs:     journalctl -u ${SERVICE_NAME} -f"
echo "  Status:   systemctl status ${SERVICE_NAME}"
