; ---------------------------------------------------------------------------
; NVRemote Host Agent — NSIS Installer
; ---------------------------------------------------------------------------
; Produces a single-EXE installer: NVRemote-Agent-Setup.exe
;
; What it does:
;   1. Checks for admin privileges
;   2. Installs nvremote-agent.exe to C:\Program Files\NVRemote
;   3. Writes agent.yaml with user-provided settings
;   4. Registers as a Windows service (NVRemoteAgent)
;   5. Creates Start Menu shortcuts & uninstaller
;   6. Registers in Add/Remove Programs
;
; Build with: makensis nvremote-agent.nsi
;   (requires NSIS 3.x — https://nsis.sourceforge.io)
; ---------------------------------------------------------------------------

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "nsDialogs.nsh"

; ---------------------------------------------------------------------------
; Metadata
; ---------------------------------------------------------------------------

!define PRODUCT_NAME    "NVRemote Host Agent"
!define PRODUCT_VERSION "0.5.2-beta"
!define PRODUCT_PUBLISHER "NVRemote"
!define PRODUCT_WEB_SITE  "https://nvremote.com"
!define INSTALL_DIR     "$PROGRAMFILES\NVRemote"
!define DATA_DIR        "$COMMONPROGRAMDATA\NVRemote"
!define SERVICE_NAME    "NVRemoteAgent"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "NVRemote-Agent-${PRODUCT_VERSION}-Setup.exe"
InstallDir "${INSTALL_DIR}"
RequestExecutionLevel admin

; ---------------------------------------------------------------------------
; UI Configuration
; ---------------------------------------------------------------------------

!define MUI_ICON "..\..\website\public\favicon.ico"
!define MUI_HEADERIMAGE
!define MUI_ABORTWARNING

; ---------------------------------------------------------------------------
; Variables for config page
; ---------------------------------------------------------------------------

Var ControlPlaneURL
Var BootstrapToken
Var HostName
Var Dialog
Var Label1
Var Label2
Var Label3
Var URLInput
Var TokenInput
Var HostNameInput

; ---------------------------------------------------------------------------
; Pages
; ---------------------------------------------------------------------------

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "..\..\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
Page custom ConfigPage ConfigPageLeave
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ---------------------------------------------------------------------------
; Config Page — collect control plane URL and bootstrap token
; ---------------------------------------------------------------------------

Function ConfigPage
  !insertmacro MUI_HEADER_TEXT "Agent Configuration" "Enter your NVRemote control plane details."

  nsDialogs::Create 1018
  Pop $Dialog
  ${If} $Dialog == error
    Abort
  ${EndIf}

  ; Control Plane URL
  ${NSD_CreateLabel} 0 0 100% 12u "Control Plane URL:"
  Pop $Label1
  ${NSD_CreateText} 0 14u 100% 12u "https://api.nvremote.com"
  Pop $URLInput

  ; Bootstrap Token
  ${NSD_CreateLabel} 0 38u 100% 12u "Bootstrap Token:"
  Pop $Label2
  ${NSD_CreateText} 0 52u 100% 12u ""
  Pop $TokenInput

  ; Host Name
  ${NSD_CreateLabel} 0 76u 100% 12u "Host Display Name (leave blank for computer name):"
  Pop $Label3
  ${NSD_CreateText} 0 90u 100% 12u "$COMPUTERNAME"
  Pop $HostNameInput

  nsDialogs::Show
FunctionEnd

Function ConfigPageLeave
  ${NSD_GetText} $URLInput $ControlPlaneURL
  ${NSD_GetText} $TokenInput $BootstrapToken
  ${NSD_GetText} $HostNameInput $HostName

  ${If} $ControlPlaneURL == ""
    MessageBox MB_ICONEXCLAMATION "Control Plane URL is required."
    Abort
  ${EndIf}

  ${If} $BootstrapToken == ""
    MessageBox MB_ICONEXCLAMATION "Bootstrap Token is required."
    Abort
  ${EndIf}

  ${If} $HostName == ""
    StrCpy $HostName "$COMPUTERNAME"
  ${EndIf}
FunctionEnd

; ---------------------------------------------------------------------------
; Install Section
; ---------------------------------------------------------------------------

Section "Install"
  SetOutPath "$INSTDIR"

  ; Stop existing service if running
  nsExec::ExecToLog 'sc stop ${SERVICE_NAME}'
  Sleep 2000
  nsExec::ExecToLog 'sc delete ${SERVICE_NAME}'
  Sleep 1000

  ; Copy files
  File "nvremote-agent.exe"

  ; Create data directory
  CreateDirectory "${DATA_DIR}"

  ; Write configuration
  FileOpen $0 "${DATA_DIR}\agent.yaml" w
  FileWrite $0 "# NVRemote Host Agent Configuration$\r$\n"
  FileWrite $0 "# Generated by installer on $%DATE%$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 'control_plane_url: "$ControlPlaneURL"$\r$\n'
  FileWrite $0 'bootstrap_token: "$BootstrapToken"$\r$\n'
  FileWrite $0 'host_name: "$HostName"$\r$\n'
  FileWrite $0 'streamer_path: "$INSTDIR\nvremote-host.exe"$\r$\n'
  FileWrite $0 "stun_servers:$\r$\n"
  FileWrite $0 '  - "stun.l.google.com:19302"$\r$\n'
  FileWrite $0 '  - "stun1.l.google.com:19302"$\r$\n'
  FileWrite $0 'data_dir: "${DATA_DIR}"$\r$\n'
  FileWrite $0 'log_level: "info"$\r$\n'
  FileClose $0

  ; Install as Windows service
  nsExec::ExecToLog '"$INSTDIR\nvremote-agent.exe" --install'

  ; Start the service
  nsExec::ExecToLog 'sc start ${SERVICE_NAME}'

  ; Create Start Menu shortcuts
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortcut "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk" "$INSTDIR\uninstall.exe"

  ; Write uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ; Register in Add/Remove Programs
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "DisplayName" "${PRODUCT_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "UninstallString" "$\"$INSTDIR\uninstall.exe$\""
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "NoRepair" 1
SectionEnd

; ---------------------------------------------------------------------------
; Uninstall Section
; ---------------------------------------------------------------------------

Section "Uninstall"
  ; Stop and remove the service
  nsExec::ExecToLog 'sc stop ${SERVICE_NAME}'
  Sleep 2000
  nsExec::ExecToLog '"$INSTDIR\nvremote-agent.exe" --uninstall'
  Sleep 1000

  ; Remove files
  Delete "$INSTDIR\nvremote-agent.exe"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"

  ; Remove Start Menu shortcuts
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk"
  RMDir "$SMPROGRAMS\${PRODUCT_NAME}"

  ; Remove registry entries
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"

  ; Ask about data directory
  MessageBox MB_YESNO "Remove configuration and data files?$\r$\n$\r$\n${DATA_DIR}" IDYES removeData IDNO keepData
  removeData:
    RMDir /r "${DATA_DIR}"
  keepData:
SectionEnd
