import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsObject,
  IsUUID,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SessionStatus } from '@prisma/client';

// ---------------------------------------------------------------------------
// Request DTOs
// ---------------------------------------------------------------------------

export class CreateSessionDto {
  @ApiProperty({ description: 'ID of the host to connect to' })
  @IsUUID()
  @IsNotEmpty()
  hostId!: string;

  @ApiProperty({
    description:
      'Base64-encoded Curve25519 public key generated by the client for WireGuard',
  })
  @IsString()
  @IsNotEmpty()
  clientPublicKey!: string;

  @ApiPropertyOptional({
    description: 'Client IP address (auto-detected if omitted)',
  })
  @IsOptional()
  @IsString()
  clientIp?: string;

  @ApiPropertyOptional({
    description: 'Arbitrary metadata about the session',
  })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Response DTOs
// ---------------------------------------------------------------------------

export class SessionResponseDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  userId!: string;

  @ApiProperty()
  hostId!: string;

  @ApiProperty({ enum: SessionStatus })
  status!: SessionStatus;

  @ApiProperty()
  startedAt!: Date;

  @ApiPropertyOptional()
  endedAt?: Date | null;

  @ApiPropertyOptional()
  clientIp?: string | null;

  @ApiPropertyOptional()
  metadata?: Record<string, unknown> | null;
}

/**
 * WireGuard tunnel parameters the client needs to configure its local
 * WireGuard interface.  The client already holds its own private key;
 * only the gateway's public key and the allocated tunnel address are new.
 */
export class WireGuardConnectionInfoDto {
  @ApiProperty({
    description: 'Allocated tunnel IP for this client (e.g. 10.101.x.y/32)',
  })
  clientAddress!: string;

  @ApiProperty({
    description: "Gateway's WireGuard public key (base64)",
  })
  serverPublicKey!: string;

  @ApiProperty({
    description: "Gateway's public endpoint (ip:port)",
  })
  serverEndpoint!: string;

  @ApiProperty({
    description: 'CIDR range the tunnel should route (10.100.0.0/16)',
  })
  allowedIps!: string;

  @ApiProperty({
    description: 'DNS server inside the tunnel (10.100.0.1)',
  })
  dns!: string;
}

/**
 * Ports exposed by the Geronimo streaming agent on the host.
 */
export class GeronimoPortsDto {
  @ApiProperty()
  video!: number;

  @ApiProperty()
  audio!: number;

  @ApiProperty()
  input!: number;
}

/**
 * Geronimo (nvstreamer host agent) connection details visible through the tunnel.
 */
export class GeronimoConnectionInfoDto {
  @ApiProperty({ description: "Host's tunnel IP (e.g. 10.100.x.y)" })
  hostIp!: string;

  @ApiProperty({ description: 'Streaming ports on the host' })
  ports!: GeronimoPortsDto;
}

/**
 * Full connection payload returned by POST /hosts/:id/connect.
 *
 * The client uses this to configure its local WireGuard interface and to
 * know where to send the video/audio/input streams through the tunnel.
 */
export class SessionConnectionInfoDto {
  @ApiProperty()
  sessionId!: string;

  @ApiProperty({ description: 'WireGuard tunnel configuration for the client' })
  wireguard!: WireGuardConnectionInfoDto;

  @ApiProperty({ description: 'Geronimo streaming host details' })
  geronimo!: GeronimoConnectionInfoDto;
}
