import {
  Controller,
  Post,
  Param,
  Body,
  UseGuards,
  ParseUUIDPipe,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiBearerAuth,
  ApiCreatedResponse,
} from '@nestjs/swagger';
import { IsString, IsNotEmpty } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import {
  CurrentUser,
  JwtPayload,
} from '../common/decorators/current-user.decorator';
import { SessionsService } from '../sessions/sessions.service';
import { SessionConnectionInfoDto } from '../sessions/dto/sessions.dto';

// ---------------------------------------------------------------------------
// DTO
// ---------------------------------------------------------------------------

export class ConnectDto {
  @ApiProperty({
    description:
      'Base64-encoded Curve25519 public key generated by the client for WireGuard',
  })
  @IsString()
  @IsNotEmpty()
  clientPublicKey!: string;
}

// ---------------------------------------------------------------------------
// Controller
// ---------------------------------------------------------------------------

/**
 * Handles POST /hosts/:id/connect -- the primary endpoint the client app
 * calls to establish a streaming session with a host.
 *
 * The client generates its own WireGuard X25519 keypair locally and sends
 * only the public key.  The server registers that public key with the
 * gateway and returns everything the client needs to configure its local
 * WireGuard interface plus the streaming connection details.
 */
@ApiTags('hosts')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller('hosts')
export class ConnectController {
  constructor(private readonly sessionsService: SessionsService) {}

  @Post(':id/connect')
  @ApiOperation({
    summary: 'Connect to a host and start a streaming session',
    description:
      'Creates a session, registers the client WireGuard peer with the gateway, ' +
      'and returns the tunnel + streaming configuration.',
  })
  @ApiCreatedResponse({
    type: SessionConnectionInfoDto,
    description: 'Connection details for WireGuard tunnel and streaming',
  })
  async connect(
    @Param('id', ParseUUIDPipe) hostId: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: ConnectDto,
  ): Promise<SessionConnectionInfoDto> {
    return this.sessionsService.createSession(user.sub, {
      hostId,
      clientPublicKey: dto.clientPublicKey,
    });
  }
}
